spring.profiles.default=local

schema-catalog.mode=${SCHEMA_CATALOG_MODE:confluent}

confluent.schema-registry.url=${CONFLUENT_SCHEMA_REGISTRY_URL:}
confluent.schema-registry.username=${CONFLUENT_SCHEMA_REGISTRY_USERNAME:}
confluent.schema-registry.password=${CONFLUENT_SCHEMA_REGISTRY_PASSWORD:}
confluent.schema-registry.api-key=${CONFLUENT_SCHEMA_REGISTRY_API_KEY:}
confluent.schema-registry.api-secret=${CONFLUENT_SCHEMA_REGISTRY_API_SECRET:}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
