spring.profiles.default=local

schema-catalog.mode=confluent

confluent.schema-registry.url=http://localhost:8081
confluent.schema-registry.username=
confluent.schema-registry.password=
confluent.schema-registry.api-key=
confluent.schema-registry.api-secret=

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
