package ru.kpfu.itis.efremov.schemarisk.analysis.diff;

public enum FieldChangeType {
    ADDED,
    REMOVED,
    TYPE_CHANGED,
    REQUIRED_ADDED,
    OPTIONAL_ADDED,
    REQUIRED_BECAME_OPTIONAL,
    OPTIONAL_BECAME_REQUIRED,
    ENUM_RESTRICTED,
    ENUM_EXPANDED,
    CONST_CHANGED,
    ADDITIONAL_PROPERTIES_DISABLED,
    ADDITIONAL_PROPERTIES_ENABLED,
    STRING_CONSTRAINT_TIGHTENED,
    STRING_CONSTRAINT_RELAXED,
    NUMERIC_CONSTRAINT_TIGHTENED,
    NUMERIC_CONSTRAINT_RELAXED,
    ARRAY_CONSTRAINT_CHANGED,
    COMPOSITION_CHANGED,
    FIELD_NAME_CHANGED,
    FIELD_LABEL_CHANGED,
    FIELD_NUMBER_REUSED,
    FIELD_REMOVED_WITHOUT_RESERVED,
    RESERVED_NUMBER_ADDED,
    RESERVED_NUMBER_REMOVED,
    ONEOF_ADDED,
    ONEOF_REMOVED,
    FIELD_MOVED_TO_ONEOF,
    FIELD_REMOVED_FROM_ONEOF,
    ENUM_VALUE_ADDED,
    ENUM_VALUE_REMOVED,
    ENUM_VALUE_NUMBER_REUSED,
    ENUM_VALUE_NAME_CHANGED,
    MAP_TYPE_CHANGED,
    WIRE_TYPE_CHANGED,
    NULLABILITY_CHANGED,
    DEFAULT_ADDED,
    DEFAULT_REMOVED,
    DEFAULT_CHANGED,
    NESTED_CHANGED,
    OTHER
}





